package com.vz.vzordercase;

import org.jbpm.casemgmt.api.model.instance.CaseFileInstance;
import com.vz.vzordercase.Order;
import com.vz.vzordercase.Product;
import java.util.Map;
import java.util.Map.Entry;

rule "Process selection dataPrep"
	dialect "mvel"
    when
        $caseData : CaseFileInstance()
        $order : Order() from $caseData.getData("caseFile_order")
        $product : Product() from $order.getProducts()
    then
     insert($product);
     System.out.println("prodcut inserted into memory" + $product.getName());
     end
rule "Process selection dataPrep1"
	dialect "mvel"
    when
        $caseData : CaseFileInstance()
        $order : Order() from $caseData.getData("caseFile_order")
       
    then
     System.out.println("order" + $order.getCustomerName());
     end
     rule "Process selection order"
	dialect "mvel"
    when
        $caseData : CaseFileInstance()
        $order : Order() from $caseData.getData("order")
       
    then
     System.out.println("order" + $order.getCustomerName());
     end
     rule "Process selection dataPrep2"
	dialect "mvel"
    when
        $caseData : CaseFileInstance()

    then
     System.out.println("order 191919" );
     end

