package com.vz.vzordercase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String name;
	private java.lang.String type;

	private java.lang.String process;

	public Product() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getProcess() {
		return this.process;
	}

	public void setProcess(java.lang.String process) {
		this.process = process;
	}

	public Product(java.lang.String id, java.lang.String name,
			java.lang.String type, java.lang.String process) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.process = process;
	}

}